name: Local - Proyecto Web y Móvil
values:
  - key: baseUrl
    value: 'http://localhost:3000/api'
  - key: token
    value: ''
  - key: solicitudId
    value: ''
  - key: documentoId
    value: ''
  - key: tokenCiudadano
    value: ''
  - key: tokenFuncionario
    value: ''
color: 0
